### ISSUE TITLE
Buat ulang API read course

### ISSUE THREAD

**Issue by itsfaqih** [zuhdifikri/neoci#2]
Data yang direturn oleh API /course/read harus berformat seperti ini:
```
{
    id: 1,
    title: 'Advanced Digital Painting',
    level: 'Intermediate',
    thumbnail: 'faiz-azhar-landscapefin.jpg',
    category: 'Design',
    author: 'Faiz Azhar',
    chapterCount: 5
}
```

**Comment by zuhdifikri** [comment]
ngecek e py :v

**Comment by itsfaqih** [comment]
nggo iki
`SELECT *, (SELECT CONCAT(first_name, ' ', last_name) FROM users WHERE id = courses.user_id) AS 'Author', (SELECT COUNT(*) FROM course_chapters WHERE course_id = courses.id) AS 'chapterCount' FROM courses`

fixed
