### ISSUE TITLE
Buat function untuk relasi

### ISSUE THREAD

**Issue by itsfaqih** [zuhdifikri/neoci#3]
Misal pada tabel users yang memiliki relasi dengan tabel user_details, fungsi yang dibuat adalah seperti ini:

```
// Controller User
public function has_details($id)
{
    $users = $this->User_model->user_details($id);

    $this->output->set_status_header(200);
    $this->output->set_output(json_encode($users));
 }
```

```
// Model User 
public function user_details($id)
{
    $this->db->select('*');
    $this->db->join($this->table_details, $this->table_details.'.id='.$this->table.'.id');
    $query = $this->db->get_where($this->table, [$this->table.'.id' => $id]);
    return $query->row();
}
```

Jadi endpoint /user/has_details/1 akan mereturn data user sekaligus data detailnya.
Lakukan hal yang sama pada user-course, course-chapter, chapter-episode, dll

**Comment by zuhdifikri** [comment]
udah tur mbuh penempatane aku pake imajinasi ..

**Comment by itsfaqih** [comment]
Jangan lupa mention pull requestnya nanti
![image](https://user-images.githubusercontent.com/48067039/72153269-0357d480-33e0-11ea-9fc5-dcb9522af283.png)
